Generative kaleidescope
patriciogonzalezvivo/lygia pull request #96
Opened 2023-08-22 15:47 UTC by kfahn22

I have adapted this [shader](https://www.shadertoy.com/view/ctByWz) to create a function that generates a kaleidoscope  pattern.  I think it creates some pretty cool effects, but you can decide.  https://editor.p5js.org/kfahn/sketches/I29DSDQOS
![kaleidescope](https://github.com/patriciogonzalezvivo/lygia/assets/65121394/21b603b3-2a3f-4852-8302-7ded78510044)

2023-08-22 16:16 UTC, patriciogonzalezvivo requested changes
this feels more like a `lygia/space` operation that a `lygia/generative`
Consider returning a `vec2` with a mirrored/kaleidoscopic space

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +    vec3 r = u_resolution.xxx;
`vec3` > `float3`

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.glsl
> +    vec3 r = u_resolution.xxx;
we can not warranty the presence of `u_resolution` uniform

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.glsl
> +    uv.z = sineIn(u_time*speed);
we can not warranty the presence of `u_time` uniform

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.glsl
> +    uv.z = sineIn(u_time*speed);
What's `sineIn` ? is not native, right?

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +    #ifdef PLATFORM_WEBGL
No need to do WEBGL version in HLSL

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +    uv = float3(lengthSq( uv ) * 0.5) ;
`float3()` takes 3 arguments

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +    vec3 uv = vec3((2.0 * st.xyy- r)/r.x * zoom);
`vec3` > `float3`
`float3` takes 3 arguments

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +description: |
Add `original_author` field

2023-08-22 16:16 UTC, patriciogonzalezvivo commented on generative/kaleidescope.hlsl
> +    uv.z = sineIn(u_time*speed);
What's `sineIn()` ?

2023-08-22 18:35 UTC, kfahn22 commented
Thanks for the feedback!  I have tried to address all of your comments. The files have been moved to space and the function now returns a vec2/float2.  Please let me know if you have any more feedback/requested changes.

2023-08-23 13:45 UTC, patriciogonzalezvivo requested changes
This doesn't seams to return a `vec2` coordinate space. Seams to specific of an algorithm.
Could be generalize so it mirrors and fract an 2D space into N sections like kaleidoscopes do?

2023-08-23 13:45 UTC, patriciogonzalezvivo commented on space/kaleidescope.glsl
> +#include "..animation/easing/sineIn.glsl"
correct path is `#include "../animation/easing/sine.glsl"`

2023-08-23 13:45 UTC, patriciogonzalezvivo commented on space/kaleidescope.glsl
> +vec2 kaleidescope( vec2 st, vec2 pixel, float t, float zoom, float m, float n, int N) {
I believe maybe the right name is "kaleidoscope" ?

2023-08-23 20:19 UTC, kfahn22 commented
I am not sure if this is what you have in mind?  Or more subdivisions?
https://editor.p5js.org/kfahn/sketches/3ZmPyZVjv
<img width="505" alt="Screenshot 2023-08-23 at 4 12 09 PM" src="https://github.com/patriciogonzalezvivo/lygia/assets/65121394/6375fbbc-9b9b-4b0b-91a3-09e3d6cf9910">

2023-08-23 23:29 UTC, closed without merging